/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import BEU.Curso;
import BEU.Estudiante;
import BLL.GestionCurso;
import BLL.GestionEstudiante;
import BLL.GestionMatricula;
import Rugel.Util;
import java.io.IOException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author labctr
 */
public class frmRegistroMatricula extends javax.swing.JInternalFrame {

    private final String titulo = "Registro de Matricula";
    private GestionCurso cursoBll = new GestionCurso();
    private GestionEstudiante estudiantesBll = new GestionEstudiante();
    private GestionMatricula matriculaBll = new GestionMatricula();
    private List<Curso> cursos;
    private List<Estudiante> estudiantes;

    private boolean Validar() {
        Curso cr = (Curso) this.cmbCursos.getSelectedItem();
        if (cr.getTitulo().equals("--Selecione--")) {
            VtnPrincipal.verMensaje("Curso no valido", titulo, JOptionPane.WARNING_MESSAGE);
            return false;
        }
        Estudiante est = (Estudiante) this.cmbEstudiantes.getSelectedItem();
        if (est.getNombre().equals("--Selecione--")) {
            VtnPrincipal.verMensaje("Estudiante no valido", titulo, JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    private void CrearMatricula() throws IOException {
            Curso cr = (Curso) this.cmbCursos.getSelectedItem();
            Estudiante est = (Estudiante) this.cmbEstudiantes.getSelectedItem();
            matriculaBll.crear();
            matriculaBll.configurar(cr, est);
            matriculaBll.archivar();
        
    }

    private void leerCursos() {
        try {
            Curso ficticio = new Curso("--Selecione--", 0.0f, "");
            this.cmbCursos.addItem(ficticio);
            cursos = cursoBll.getCursos();
            //expersion lamba
            cursos.forEach((c) -> {
                this.cmbCursos.addItem(c);
            });
        } catch (Exception e) {
            Util.imprimir("Error: " + e.toString());
            VtnPrincipal.verMensaje("Error al leer cursos ", titulo, JOptionPane.ERROR_MESSAGE);
        }
    }

    private void leerEstudiantes() {
        try {
            Estudiante ficticio = new Estudiante();
            ficticio.setNombre("--Selecione--");
            ficticio.setApellido("");
            this.cmbEstudiantes.addItem(ficticio);
            estudiantes = estudiantesBll.leerEstudiantes();
            estudiantes.forEach((e) -> {
                this.cmbEstudiantes.addItem(e);
            });
        } catch (Exception e) {
            Util.imprimir("Error: " + e.toString());
            VtnPrincipal.verMensaje("Error al leer estudiantes ", titulo, JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * Creates new form frmRegistroMatricula
     */
    public frmRegistroMatricula() {
        initComponents();
        leerCursos();
        leerEstudiantes();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegistro = new javax.swing.JLabel();
        lblEstudiante = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        cmbEstudiantes = new javax.swing.JComboBox<>();
        cmbCursos = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lblRegistro.setFont(new java.awt.Font("Ubuntu Light", 3, 36)); // NOI18N
        lblRegistro.setForeground(new java.awt.Color(214, 23, 15));
        lblRegistro.setText("Registro de Matricula");

        lblEstudiante.setFont(new java.awt.Font("TlwgMono", 1, 18)); // NOI18N
        lblEstudiante.setText("Estudiante : ");

        lblCurso.setFont(new java.awt.Font("TlwgMono", 1, 18)); // NOI18N
        lblCurso.setText("Curso : ");

        btnGuardar.setFont(new java.awt.Font("URW Palladio L", 3, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstudiante)
                            .addComponent(lblCurso))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCursos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbEstudiantes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 197, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblRegistro)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstudiante)
                    .addComponent(cmbEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurso)
                    .addComponent(cmbCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            if(Validar()){
            CrearMatricula();
            VtnPrincipal.verMensaje("Matricula creada corectamente", titulo, JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            Util.imprimir("Error: " + e.toString());
            VtnPrincipal.verMensaje("Error al crear la Matricula ", titulo, JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<Curso> cmbCursos;
    private javax.swing.JComboBox<Estudiante> cmbEstudiantes;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblEstudiante;
    private javax.swing.JLabel lblRegistro;
    // End of variables declaration//GEN-END:variables
}
